// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT count(*) FROM application_users
WHERE organization_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) CountActiveUsers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOtherActiveAdmins = `-- name: CountOtherActiveAdmins :one
SELECT count(*) FROM application_users
WHERE organization_id = $1 AND id <> $2
  AND status = 'ACTIVE' AND application_role = 'administrator'
`

type CountOtherActiveAdminsParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

// Administrator aktif selain satu pengguna: pemasangan tidak boleh
// kehilangan administrator terakhirnya lewat layar.
func (q *Queries) CountOtherActiveAdmins(ctx context.Context, arg CountOtherActiveAdminsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveAdmins, arg.OrganizationID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM application_users WHERE organization_id = $1
`

// Termasuk yang di-suspend: pemasangan yang pernah memberi akses kepada
// siapa pun bukan lagi pemasangan kosong.
func (q *Queries) CountUsers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginAttempt = `-- name: CreateLoginAttempt :exec
INSERT INTO login_attempts (token_hash, state, nonce, verifier, return_to, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLoginAttemptParams struct {
	TokenHash []byte
	State     string
	Nonce     string
	Verifier  string
	ReturnTo  *string
	ExpiresAt time.Time
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, createLoginAttempt,
		arg.TokenHash,
		arg.State,
		arg.Nonce,
		arg.Verifier,
		arg.ReturnTo,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    organization_id, application_user_id, token_hash, expires_at,
    auth_kind, refresh_token, id_token, last_checked_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type CreateSessionParams struct {
	OrganizationID    uuid.UUID
	ApplicationUserID uuid.UUID
	TokenHash         []byte
	ExpiresAt         time.Time
	AuthKind          string
	RefreshToken      *string
	IDToken           *string
	LastCheckedAt     *time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.OrganizationID,
		arg.ApplicationUserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.AuthKind,
		arg.RefreshToken,
		arg.IDToken,
		arg.LastCheckedAt,
	)
	return err
}

const deleteExpiredLoginAttempts = `-- name: DeleteExpiredLoginAttempts :exec
DELETE FROM login_attempts WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredLoginAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredLoginAttempts)
	return err
}

const findActiveUser = `-- name: FindActiveUser :one
SELECT id FROM application_users
WHERE organization_id = $1 AND external_subject = $2
  AND status = 'ACTIVE'
`

type FindActiveUserParams struct {
	OrganizationID  uuid.UUID
	ExternalSubject string
}

func (q *Queries) FindActiveUser(ctx context.Context, arg FindActiveUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveUser, arg.OrganizationID, arg.ExternalSubject)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAccessEvent = `-- name: InsertAccessEvent :exec
INSERT INTO user_access_events (
    organization_id, application_user_id, action, role_before, role_after,
    source, actor_user_id, actor_name
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
`

type InsertAccessEventParams struct {
	OrganizationID    uuid.UUID
	ApplicationUserID uuid.UUID
	Action            string
	RoleBefore        *string
	RoleAfter         *string
	Source            string
	ActorUserID       *uuid.UUID
	ActorName         string
}

func (q *Queries) InsertAccessEvent(ctx context.Context, arg InsertAccessEventParams) error {
	_, err := q.db.Exec(ctx, insertAccessEvent,
		arg.OrganizationID,
		arg.ApplicationUserID,
		arg.Action,
		arg.RoleBefore,
		arg.RoleAfter,
		arg.Source,
		arg.ActorUserID,
		arg.ActorName,
	)
	return err
}

const listAccessEvents = `-- name: ListAccessEvents :many
SELECT action, role_before, role_after, source, actor_name, occurred_at
FROM user_access_events
WHERE organization_id = $1 AND application_user_id = $2
ORDER BY occurred_at, id
`

type ListAccessEventsParams struct {
	OrganizationID    uuid.UUID
	ApplicationUserID uuid.UUID
}

type ListAccessEventsRow struct {
	Action     string
	RoleBefore *string
	RoleAfter  *string
	Source     string
	ActorName  string
	OccurredAt time.Time
}

func (q *Queries) ListAccessEvents(ctx context.Context, arg ListAccessEventsParams) ([]ListAccessEventsRow, error) {
	rows, err := q.db.Query(ctx, listAccessEvents, arg.OrganizationID, arg.ApplicationUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessEventsRow{}
	for rows.Next() {
		var i ListAccessEventsRow
		if err := rows.Scan(
			&i.Action,
			&i.RoleBefore,
			&i.RoleAfter,
			&i.Source,
			&i.ActorName,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, external_subject, email, name, application_role, status,
       last_login_at, created_at
FROM application_users
WHERE organization_id = $1
ORDER BY created_at, id
`

type ListUsersRow struct {
	ID              uuid.UUID
	ExternalSubject string
	Email           *string
	Name            *string
	ApplicationRole string
	Status          string
	LastLoginAt     *time.Time
	CreatedAt       time.Time
}

func (q *Queries) ListUsers(ctx context.Context, organizationID uuid.UUID) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalSubject,
			&i.Email,
			&i.Name,
			&i.ApplicationRole,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionForRecheck = `-- name: LockSessionForRecheck :one
SELECT refresh_token, last_checked_at
FROM sessions
WHERE id = $1 AND revoked_at IS NULL
FOR UPDATE
`

type LockSessionForRecheckRow struct {
	RefreshToken  *string
	LastCheckedAt *time.Time
}

// Pemeriksaan ulang pencabutan dikunci per sesi: refresh token dapat dirotasi
// pada setiap penukaran, dan dua request yang menukar token yang sama akan
// membuat yang kedua ditolak walau orangnya masih berhak.
func (q *Queries) LockSessionForRecheck(ctx context.Context, id uuid.UUID) (LockSessionForRecheckRow, error) {
	row := q.db.QueryRow(ctx, lockSessionForRecheck, id)
	var i LockSessionForRecheckRow
	err := row.Scan(&i.RefreshToken, &i.LastCheckedAt)
	return i, err
}

const lockUserGrants = `-- name: LockUserGrants :exec
SELECT pg_advisory_xact_lock(hashtext('users.grant.' || $1::text))
`

// Pemberian akses dari satu pemasangan tidak berjalan bersamaan: kuota
// users.max dihitung lalu ditulis dalam transaksi yang sama.
func (q *Queries) LockUserGrants(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, lockUserGrants, organizationID)
	return err
}

const recordLogin = `-- name: RecordLogin :one
UPDATE application_users
SET last_login_at = now(), updated_at = now(),
    email = COALESCE($1, email),
    name = COALESCE($2, name)
WHERE organization_id = $3 AND external_subject = $4
  AND status = 'ACTIVE'
RETURNING id
`

type RecordLoginParams struct {
	Email           *string
	Name            *string
	OrganizationID  uuid.UUID
	ExternalSubject string
}

// Nama dan email mengikuti GONSU pada setiap login; yang kosong di token
// tidak menghapus yang tersimpan.
func (q *Queries) RecordLogin(ctx context.Context, arg RecordLoginParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, recordLogin,
		arg.Email,
		arg.Name,
		arg.OrganizationID,
		arg.ExternalSubject,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const recordRecheck = `-- name: RecordRecheck :exec
UPDATE sessions
SET refresh_token = $1, last_checked_at = $2
WHERE id = $3
`

type RecordRecheckParams struct {
	RefreshToken  *string
	LastCheckedAt *time.Time
	ID            uuid.UUID
}

func (q *Queries) RecordRecheck(ctx context.Context, arg RecordRecheckParams) error {
	_, err := q.db.Exec(ctx, recordRecheck, arg.RefreshToken, arg.LastCheckedAt, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :one
UPDATE sessions SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
RETURNING auth_kind, id_token
`

type RevokeSessionByTokenRow struct {
	AuthKind string
	IDToken  *string
}

func (q *Queries) RevokeSessionByToken(ctx context.Context, tokenHash []byte) (RevokeSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeSessionByToken, tokenHash)
	var i RevokeSessionByTokenRow
	err := row.Scan(&i.AuthKind, &i.IDToken)
	return i, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE organization_id = $1 AND application_user_id = $2
  AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	OrganizationID    uuid.UUID
	ApplicationUserID uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.OrganizationID, arg.ApplicationUserID)
	return err
}

const sessionPrincipal = `-- name: SessionPrincipal :one
SELECT s.id AS session_id, s.auth_kind, s.last_checked_at,
       u.id AS user_id, u.organization_id, u.name, u.email, u.application_role
FROM sessions s
JOIN application_users u
  ON u.organization_id = s.organization_id AND u.id = s.application_user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.status = 'ACTIVE'
`

type SessionPrincipalRow struct {
	SessionID       uuid.UUID
	AuthKind        string
	LastCheckedAt   *time.Time
	UserID          uuid.UUID
	OrganizationID  uuid.UUID
	Name            *string
	Email           *string
	ApplicationRole string
}

// Sesi hanya berlaku bila belum dicabut, belum kedaluwarsa, dan penggunanya
// masih ACTIVE di application_users — pengguna yang di-suspend kehilangan
// aksesnya pada permintaan berikutnya, bukan saat sesinya habis.
func (q *Queries) SessionPrincipal(ctx context.Context, tokenHash []byte) (SessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, sessionPrincipal, tokenHash)
	var i SessionPrincipalRow
	err := row.Scan(
		&i.SessionID,
		&i.AuthKind,
		&i.LastCheckedAt,
		&i.UserID,
		&i.OrganizationID,
		&i.Name,
		&i.Email,
		&i.ApplicationRole,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE application_users
SET application_role = $1, updated_at = now()
WHERE organization_id = $2 AND id = $3
`

type SetUserRoleParams struct {
	ApplicationRole string
	OrganizationID  uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ApplicationRole, arg.OrganizationID, arg.ID)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE application_users SET status = $1, updated_at = now()
WHERE organization_id = $2 AND id = $3
`

type SetUserStatusParams struct {
	Status         string
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.Status, arg.OrganizationID, arg.ID)
	return err
}

const subjectGranted = `-- name: SubjectGranted :one
SELECT EXISTS (
    SELECT 1 FROM application_users
    WHERE organization_id = $1 AND external_subject = $2
      AND status = 'ACTIVE'
)
`

type SubjectGrantedParams struct {
	OrganizationID  uuid.UUID
	ExternalSubject string
}

// Diberi akses = ada baris ACTIVE dengan `sub` ini di pemasangan ini.
// Kuncinya external_subject, tidak pernah email.
func (q *Queries) SubjectGranted(ctx context.Context, arg SubjectGrantedParams) (bool, error) {
	row := q.db.QueryRow(ctx, subjectGranted, arg.OrganizationID, arg.ExternalSubject)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const suspendUser = `-- name: SuspendUser :one
UPDATE application_users SET status = 'SUSPENDED', updated_at = now()
WHERE organization_id = $1 AND external_subject = $2
RETURNING id
`

type SuspendUserParams struct {
	OrganizationID  uuid.UUID
	ExternalSubject string
}

func (q *Queries) SuspendUser(ctx context.Context, arg SuspendUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, suspendUser, arg.OrganizationID, arg.ExternalSubject)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const takeLoginAttempt = `-- name: TakeLoginAttempt :one
DELETE FROM login_attempts
WHERE token_hash = $1 AND expires_at > now()
RETURNING state, nonce, verifier, return_to
`

type TakeLoginAttemptRow struct {
	State    string
	Nonce    string
	Verifier string
	ReturnTo *string
}

// Dihapus saat dipakai: balikan yang sama tidak dapat diputar ulang.
func (q *Queries) TakeLoginAttempt(ctx context.Context, tokenHash []byte) (TakeLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, takeLoginAttempt, tokenHash)
	var i TakeLoginAttemptRow
	err := row.Scan(
		&i.State,
		&i.Nonce,
		&i.Verifier,
		&i.ReturnTo,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO application_users (organization_id, external_subject, email, name, application_role)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, external_subject) DO UPDATE
SET email = COALESCE(EXCLUDED.email, application_users.email),
    name = COALESCE(EXCLUDED.name, application_users.name),
    application_role = EXCLUDED.application_role,
    status = 'ACTIVE',
    updated_at = now()
RETURNING id
`

type UpsertUserParams struct {
	OrganizationID  uuid.UUID
	ExternalSubject string
	Email           *string
	Name            *string
	ApplicationRole string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OrganizationID,
		arg.ExternalSubject,
		arg.Email,
		arg.Name,
		arg.ApplicationRole,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const userByID = `-- name: UserByID :one
SELECT id, external_subject, status, application_role
FROM application_users
WHERE organization_id = $1 AND id = $2
`

type UserByIDParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type UserByIDRow struct {
	ID              uuid.UUID
	ExternalSubject string
	Status          string
	ApplicationRole string
}

func (q *Queries) UserByID(ctx context.Context, arg UserByIDParams) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, arg.OrganizationID, arg.ID)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalSubject,
		&i.Status,
		&i.ApplicationRole,
	)
	return i, err
}

const userBySubject = `-- name: UserBySubject :one
SELECT id, status, application_role FROM application_users
WHERE organization_id = $1 AND external_subject = $2
`

type UserBySubjectParams struct {
	OrganizationID  uuid.UUID
	ExternalSubject string
}

type UserBySubjectRow struct {
	ID              uuid.UUID
	Status          string
	ApplicationRole string
}

func (q *Queries) UserBySubject(ctx context.Context, arg UserBySubjectParams) (UserBySubjectRow, error) {
	row := q.db.QueryRow(ctx, userBySubject, arg.OrganizationID, arg.ExternalSubject)
	var i UserBySubjectRow
	err := row.Scan(&i.ID, &i.Status, &i.ApplicationRole)
	return i, err
}
