// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const claimInstallation = `-- name: ClaimInstallation :exec
INSERT INTO installation (organization_id, gonsu_organization_id)
VALUES ($1, $2)
ON CONFLICT (singleton) DO NOTHING
`

type ClaimInstallationParams struct {
	OrganizationID      uuid.UUID
	GonsuOrganizationID *string
}

// Replica yang start bersamaan masing-masing membawa kandidat; yang pertama
// menang dan semuanya membaca nilai yang sama.
func (q *Queries) ClaimInstallation(ctx context.Context, arg ClaimInstallationParams) error {
	_, err := q.db.Exec(ctx, claimInstallation, arg.OrganizationID, arg.GonsuOrganizationID)
	return err
}

const installation = `-- name: Installation :one
SELECT organization_id, gonsu_organization_id FROM installation
`

type InstallationRow struct {
	OrganizationID      uuid.UUID
	GonsuOrganizationID *string
}

func (q *Queries) Installation(ctx context.Context) (InstallationRow, error) {
	row := q.db.QueryRow(ctx, installation)
	var i InstallationRow
	err := row.Scan(&i.OrganizationID, &i.GonsuOrganizationID)
	return i, err
}

const recordGonsuOrganization = `-- name: RecordGonsuOrganization :exec
UPDATE installation SET gonsu_organization_id = $1
WHERE gonsu_organization_id IS NULL
`

// ID kanonik GONSU dicatat sekali; pemasangan tidak berpindah organization.
func (q *Queries) RecordGonsuOrganization(ctx context.Context, gonsuOrganizationID *string) error {
	_, err := q.db.Exec(ctx, recordGonsuOrganization, gonsuOrganizationID)
	return err
}
