// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type ApplicationUser struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	ExternalSubject string
	Email           *string
	Name            *string
	ApplicationRole string
	Status          string
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type IdempotencyKey struct {
	OrganizationID     uuid.UUID
	Endpoint           string
	IdempotencyKey     string
	RequestFingerprint string
	ResponseStatus     *int32
	ResponseBody       []byte
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

type Installation struct {
	Singleton           bool
	OrganizationID      uuid.UUID
	GonsuOrganizationID *string
	CreatedAt           time.Time
}

type LoginAttempt struct {
	TokenHash []byte
	State     string
	Nonce     string
	Verifier  string
	ReturnTo  *string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Note struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Title          string
	Body           string
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Session struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	ApplicationUserID uuid.UUID
	TokenHash         []byte
	AuthKind          string
	RefreshToken      *string
	IDToken           *string
	LastCheckedAt     *time.Time
	CreatedAt         time.Time
	ExpiresAt         time.Time
	RevokedAt         *time.Time
}

type UserAccessEvent struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	ApplicationUserID uuid.UUID
	Action            string
	RoleBefore        *string
	RoleAfter         *string
	Source            string
	ActorUserID       *uuid.UUID
	ActorName         string
	OccurredAt        time.Time
}
