// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimKey = `-- name: ClaimKey :one
INSERT INTO idempotency_keys (organization_id, endpoint, idempotency_key, request_fingerprint, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, endpoint, idempotency_key) DO UPDATE
    SET request_fingerprint = EXCLUDED.request_fingerprint,
        response_status     = NULL,
        response_body       = NULL,
        created_at          = now(),
        expires_at          = EXCLUDED.expires_at
    WHERE idempotency_keys.expires_at <= now()
RETURNING idempotency_key
`

type ClaimKeyParams struct {
	OrganizationID     uuid.UUID
	Endpoint           string
	IdempotencyKey     string
	RequestFingerprint string
	ExpiresAt          time.Time
}

// Mengembalikan baris hanya bila key baru diklaim — atau diklaim ulang karena
// yang lama sudah kedaluwarsa. Tanpa baris berarti key yang sama masih hidup.
func (q *Queries) ClaimKey(ctx context.Context, arg ClaimKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimKey,
		arg.OrganizationID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ExpiresAt,
	)
	var idempotency_key string
	err := row.Scan(&idempotency_key)
	return idempotency_key, err
}

const completeKey = `-- name: CompleteKey :exec
UPDATE idempotency_keys
SET response_status = $1, response_body = $2
WHERE organization_id = $3
  AND endpoint = $4
  AND idempotency_key = $5
`

type CompleteKeyParams struct {
	ResponseStatus *int32
	ResponseBody   []byte
	OrganizationID uuid.UUID
	Endpoint       string
	IdempotencyKey string
}

func (q *Queries) CompleteKey(ctx context.Context, arg CompleteKeyParams) error {
	_, err := q.db.Exec(ctx, completeKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.OrganizationID,
		arg.Endpoint,
		arg.IdempotencyKey,
	)
	return err
}

const getKey = `-- name: GetKey :one
SELECT request_fingerprint, response_status, response_body
FROM idempotency_keys
WHERE organization_id = $1
  AND endpoint = $2
  AND idempotency_key = $3
  AND expires_at > now()
`

type GetKeyParams struct {
	OrganizationID uuid.UUID
	Endpoint       string
	IdempotencyKey string
}

type GetKeyRow struct {
	RequestFingerprint string
	ResponseStatus     *int32
	ResponseBody       []byte
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (GetKeyRow, error) {
	row := q.db.QueryRow(ctx, getKey, arg.OrganizationID, arg.Endpoint, arg.IdempotencyKey)
	var i GetKeyRow
	err := row.Scan(&i.RequestFingerprint, &i.ResponseStatus, &i.ResponseBody)
	return i, err
}
