// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (organization_id, title, body, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateNoteParams struct {
	OrganizationID uuid.UUID
	Title          string
	Body           string
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.OrganizationID,
		arg.Title,
		arg.Body,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE organization_id = $1 AND id = $2
`

type DeleteNoteParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT n.id, n.title, n.body, n.created_at, n.updated_at, u.name AS created_by_name
FROM notes n
JOIN application_users u ON u.organization_id = n.organization_id AND u.id = n.created_by
WHERE n.organization_id = $1 AND n.id = $2
`

type GetNoteParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetNoteRow struct {
	ID            uuid.UUID
	Title         string
	Body          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedByName *string
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (GetNoteRow, error) {
	row := q.db.QueryRow(ctx, getNote, arg.OrganizationID, arg.ID)
	var i GetNoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many

SELECT n.id, n.title, n.body, n.created_at, n.updated_at, u.name AS created_by_name
FROM notes n
JOIN application_users u ON u.organization_id = n.organization_id AND u.id = n.created_by
WHERE n.organization_id = $1
ORDER BY n.created_at DESC, n.id DESC
LIMIT $2
`

type ListNotesParams struct {
	OrganizationID uuid.UUID
	MaxRows        int32
}

type ListNotesRow struct {
	ID            uuid.UUID
	Title         string
	Body          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedByName *string
}

// Setiap query menyaring organization_id: tidak ada jalan membaca atau
// mengubah catatan milik pemasangan lain, walau id-nya ditebak.
func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, arg.OrganizationID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesRow{}
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :execrows
UPDATE notes SET title = $1, body = $2, updated_at = now()
WHERE organization_id = $3 AND id = $4
`

type UpdateNoteParams struct {
	Title          string
	Body           string
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.OrganizationID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
